"""makemigration: diff two staged versions via `results.temporary_local_db`."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .config import ProjectConfig
from .errors import PgpkgError
from .layout import incremental_filename


@dataclass(frozen=True)
class IncrementalResult:
    from_version: str
    to_version: str
    sql: str
    path: Path | None  # None if not written


def generate_incremental_sql(
    config: ProjectConfig,
    *,
    from_version: str,
    to_version: str,
    base_url: str = "postgresql:///postgres",
) -> str:
    """Build an incremental migration SQL by diffing two staged base files.

    Spins up two throwaway databases via `results.temporary_local_db(base_url)`,
    loads the staged base SQL for each version, and returns
    `db_from.schemadiff_as_sql(db_to)` — i.e. the SQL needed to transform `from`
    into `to`. Returns the bare diff SQL (no header). Empty string if identical.
    """
    try:
        from results.tempdb import temporary_local_db  # noqa: F401
    except ImportError as exc:  # pragma: no cover
        raise PgpkgError(
            "results library not installed. Add the 'diff' extra: pip install pgpkg[diff]",
            code="E_DIFF",
        ) from exc

    from results.tempdb import temporary_local_db

    from_path = _staged_path(config, from_version)
    to_path = _staged_path(config, to_version)
    from_sql = from_path.read_text(encoding="utf-8")
    to_sql = to_path.read_text(encoding="utf-8")

    with temporary_local_db(base_url) as db_from, temporary_local_db(base_url) as db_to:
        with db_from.t() as t:
            t.execute(from_sql)
        with db_to.t() as t:
            t.execute(to_sql)
        diff_sql: str = db_from.schemadiff_as_sql(db_to)
    return diff_sql


def write_incremental(
    config: ProjectConfig,
    *,
    from_version: str,
    to_version: str,
    base_url: str = "postgresql:///postgres",
    output_path: Path | None = None,
    overwrite: bool = True,
    prepend_files: list[Path] | None = None,
    append_files: list[Path] | None = None,
    append_sql: list[str] | None = None,
) -> IncrementalResult:
    """Generate and write an incremental migration file."""
    diff_sql = generate_incremental_sql(
        config, from_version=from_version, to_version=to_version, base_url=base_url
    )
    target = output_path or (
        config.migrations_dir / incremental_filename(config.prefix, from_version, to_version)
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not overwrite:
        raise PgpkgError(f"{target} already exists and overwrite=False", code="E_DIFF")
    body = _render_incremental_body(
        config=config,
        from_version=from_version,
        to_version=to_version,
        diff_sql=diff_sql,
        prepend_files=prepend_files or [],
        append_files=append_files or [],
        append_sql=append_sql or [],
    )
    if not body.endswith("\n"):
        body += "\n"
    target.write_text(body, encoding="utf-8")
    return IncrementalResult(
        from_version=from_version, to_version=to_version, sql=diff_sql, path=target
    )


def _render_incremental_body(
    *,
    config: ProjectConfig,
    from_version: str,
    to_version: str,
    diff_sql: str,
    prepend_files: list[Path],
    append_files: list[Path],
    append_sql: list[str],
) -> str:
    parts = [
        "-- Generated by pgpkg makemigration",
        f"-- Project: {config.project_name}",
        f"-- From:    {from_version}",
        f"-- To:      {to_version}",
        "-- Review the diff before applying.",
        "",
    ]
    parts.extend(_read_sql_block(path) for path in prepend_files)
    if diff_sql.strip():
        parts.append(diff_sql.rstrip("\n"))
    parts.extend(_read_sql_block(path) for path in append_files)
    parts.extend(sql.rstrip("\n") for sql in append_sql if sql.strip())
    return "\n".join(parts)


def _read_sql_block(path: Path) -> str:
    if not path.is_file():
        raise PgpkgError(f"SQL wrapper file not found: {path}", code="E_DIFF")
    return path.read_text(encoding="utf-8").rstrip("\n")


def _staged_path(config: ProjectConfig, version: str) -> Path:
    from .layout import base_filename

    p = config.migrations_dir / base_filename(config.prefix, version)
    if not p.is_file():
        raise PgpkgError(
            f"Staged base file for version {version!r} not found at {p}. "
            f"Run `pgpkg stageversion {version}` first.",
            code="E_DIFF",
        )
    return p
