"""stageversion: render a staged base file from sql/ fragments."""

from __future__ import annotations

from pathlib import Path

from .config import ProjectConfig
from .errors import LayoutError
from .layout import base_filename, sorted_fragments


def render_staged_sql(config: ProjectConfig, version: str) -> str:
    """Render the body of `<prefix>--<version>.sql` from the project's sql/ tree.

    The body is a deterministic concatenation of *.sql files in `sql/` (sorted by
    filename), with BEGIN/END FRAGMENT markers. Files in `sql/pre/` and `sql/post/`
    are NOT embedded — they are applied at runtime around every migration step.
    """
    sql_dir = config.sql_dir
    if not sql_dir.is_dir():
        raise LayoutError(f"sql/ directory not found at {sql_dir}")

    fragments = sorted_fragments(sql_dir)
    if not fragments:
        raise LayoutError(
            f"No *.sql files found in {sql_dir}. Add at least one fragment "
            "(files in sql/pre or sql/post are not enough)."
        )

    chunks: list[str] = [
        "-- Generated by pgpkg stageversion",
        f"-- Project: {config.project_name}",
        f"-- Version: {version}",
        "",
    ]
    for fragment in fragments:
        chunks.append(f"-- BEGIN FRAGMENT: {fragment.name}")
        chunks.append(fragment.read_text(encoding="utf-8").rstrip())
        chunks.append(f"-- END FRAGMENT: {fragment.name}")
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def write_staged_file(
    config: ProjectConfig,
    version: str,
    *,
    output_path: Path | None = None,
    overwrite: bool = True,
) -> Path:
    """Render and write the staged base file. Returns the path written."""
    body = render_staged_sql(config, version)
    target = output_path or (config.migrations_dir / base_filename(config.prefix, version))
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not overwrite:
        raise LayoutError(f"{target} already exists and overwrite=False")
    target.write_text(body, encoding="utf-8")
    return target


def read_pre_post(config: ProjectConfig) -> tuple[str, str]:
    """Concatenate sql/pre/*.sql and sql/post/*.sql.

    Returns (pre_sql, post_sql); each may be empty string.
    Files are sorted by filename. README.md and other non-.sql files are ignored.
    """
    pre = "\n".join(p.read_text(encoding="utf-8") for p in sorted_fragments(config.pre_dir))
    post = "\n".join(p.read_text(encoding="utf-8") for p in sorted_fragments(config.post_dir))
    return pre, post
